### ISSUE TITLE
My Review of touhou-bunker 

### ISSUE THREAD

**Issue by NETLIFYHOSTINGAHMD** [phrl42/touhou-bunker#2]
A VOLUME KNOB WOULD HAVE BEEN NICE!!

ALL THE GAME DID WAS BREAK MY BUILT-IN SPEAKERS AND ALSO THEY DAMAGED MY PCIE SLOT

NOT TO MENTION MY MINI PCIE SLOT WAS ALMOST CATCHING ON FIRE.

ANOTHER QUESTION I HAVE FOR THE DEVELOPER

WHY DID MY WEBCAM JUST START BURNING????

**Comment by phrl42** [comment]
ok what the hell

**Comment by NETLIFYHOSTINGAHMD** [comment]
Verificated Message From _Brandleiot Algorithms Company_ 

we can fund this

**Comment by rnbunker** [comment]
I believe I have this issues as well? Please fix this?


Just use tkinter?

**Comment by phrl42** [comment]
There is no need for any python stuff in this Project.

**Comment by rnbunker** [comment]
it would be highly beneficial? please understand?

**Comment by NETLIFYHOSTINGAHMD** [comment]
developer has a blunt-corners

**Comment by NETLIFYHOSTINGAHMD** [comment]
consider nodejs as a possibilty...,,

**Comment by phrl42** [comment]
No need for NodeJS

**Comment by rnbunker** [comment]
Yes! This could be truly revolutionary for the project!

**Comment by phrl42** [comment]
And why is that?

**Comment by NETLIFYHOSTINGAHMD** [comment]
developer does not believe this project requires pull requests!

**Comment by rnbunker** [comment]
NodeJS is faster than the ,,,SIMPLE DIRECTORY LAYER LIBRARY''' ALSO KNOWN AS "SDL" 


please consider using electron as an alternative!

**Comment by phrl42** [comment]
Feel free to make a PR anytime!

**Comment by rnbunker** [comment]
we could fund this project to bring it into the right direction!

**Comment by rnbunker** [comment]
_Verified Message from BrandeliotAlgorithmsCompany_

**Comment by NETLIFYHOSTINGAHMD** [comment]
https://github.com/phrl42/touhou-bunker/issues/2

> Feel free to make a PR anytime!
t

**Comment by rnbunker** [comment]
Why hasn't this been fixed yet???

**Comment by phrl42** [comment]
Please refer to the README.

**Comment by rnbunker** [comment]
> Feel free to make a PR anytime! But please no useless PR's. Thank you!
this is not a ,,,USELESS''' PR! you will get charged for this... this is blasphemy! Poisoning the Minds of the Youth! You are a witch!

**Comment by phrl42** [comment]
**what**
